### ISSUE TITLE
SADX closing after completing Sky Chase Act 2

### ISSUE THREAD

**Issue by Aiud1234** [X-Hax/sadx-mod-loader#137]
I tried reopening SADX over and over and over again but it doesn't work

Steps to get the crash:
1. Finish Sky Chase 2
2. Wait for the ''EGG CARRIER'' black screen
3. The game then closes

Of the bug repeating

**Comment by PiKeyAr** [comment]
Does this happen with all mods disabled? Is there a crash dump?

**Comment by Aiud1234** [comment]
> Does this happen with all mods disabled? Is there a crash dump?

I don't have one, and no, it didn't happen with all mods disabled

**Comment by PiKeyAr** [comment]
If it doesn't happen with all mods disabled, it's likely a problem with some mods rather than the Mod Loader itself. Since this repo is for Mod Loader issues only, I'm closing this. If you need help figuring out a problem with mods, check out the troubleshooting guides or ask on the troubleshooting channel on the x-hax Discord.

**Comment by Aiud1234** [comment]
Nvm, the Egg Carrier Ocean Music mod is the problem, thanks
